### ISSUE TITLE
forHtml fails to encode an Ampersand in a stringified Map

### ISSUE THREAD

**Issue by privettoli** [jmanico/owasp-java-encoder#21]
Artifact file that fails: 
[AmpersandIssue.txt](https://github.com/OWASP/owasp-java-encoder/files/2129384/AmpersandIssue.txt)

CloudFoundry buildpack: [java_buildpack_offline-3_8_1](https://github.com/cloudfoundry/java-buildpack/releases?after=v3.8.1)
OpenJDK JRE: [1.8.0_91-unlimited-crypto](https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_91-unlimited-crypto.tar.gz)
org.owasp.encoder:encoder: 1.1
org.owasp.esapi:esapi: 2.1.0.1

Also tested on: 
```ruby
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

Simple code:
```java
Encode.forHtml(new String(Files.readAllBytes(Paths.get("AmpersandIssue.txt")), UTF_8));
```
The stack trace is:
```ruby
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.String.getChars(String.java:826)
	at org.owasp.encoder.Encode$Buffer.encode(Encode.java:1306)
	at org.owasp.encoder.Encode.encode(Encode.java:1220)
	at org.owasp.encoder.Encode.forXml(Encode.java:739)
	at org.owasp.encoder.Encode.forHtml(Encode.java:155)
```

**Comment by privettoli** [comment]
Fixed by upgrading to 1.2.1
